// data/foodBusinesses.ts

import { FoodBusinessType } from "@/@types/restaurant";
import { CategoryType } from "./categories";
import { FoodCategoryItem } from "@/@types/foodCategoryTypes";

export const foodBusinesses: FoodBusinessType[] = [
  {
    id: "1",
    businessName: "Sufi House – Gulshan",
    profileImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Authentic Bangladeshi flavors",
    specialities: ["Bangladeshi", "Rice Bowl"],
    averageRating: 4.9,
    totalReviews: 120,
    minimumOrder: 250,
    deliveryFee: 40,
    availabilityStatus: "available",
    schedules: [
      { startTime: "10:00", endTime: "22:00", status: "available" },
    ],
    location: {
      address: "Road 11, Gulshan",
      city: "Dhaka",
      area: "Gulshan",
      coordinates: { lat: 23.7806, lng: 90.4228 },
    },
    deals: [
      { id: "1", title: "Tk 100 off (WELCOME)", description: "Min. order Tk 320. Valid for new users." },
      { id: "2", title: "10% off (SUFI10)", description: "Valid for all items. Use in cart." }
    ],
    categories: [
      { name: "Popular", count: 5 },
      { name: "Rice Bowl", count: 3 },
      { name: "Special", count: 2 }
    ]
  },
  {
    id: "2",
    businessName: "Tripti Catering",
    profileImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Homestyle meals with love",
    specialities: ["Catering", "Family Meals"],
    averageRating: 4.6,
    totalReviews: 540,
    minimumOrder: 300,
    deliveryFee: 45,
    availabilityStatus: "available",
    schedules: [
      { startTime: "11:00", endTime: "20:00", status: "available" },
    ],
    location: {
      address: "Banani, Block B",
      city: "Dhaka",
      area: "Banani",
      coordinates: { lat: 23.7925, lng: 90.4078 },
    },
    deals: [
      { id: "1", title: "Tk 80 off (TRIPTI80)", description: "Min. order Tk 250. Valid for all items." },
      { id: "2", title: "Free dessert (FREESWEET)", description: "On orders above Tk 500." }
    ],
    categories: [
      { name: "Family Meals", count: 4 },
      { name: "Catering", count: 2 },
      { name: "Popular", count: 3 }
    ]
  },
  {
    id: "3",
    businessName: "Burger Boss",
    profileImage: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Juiciest burgers in town",
    specialities: ["Burger", "Fast Food"],
    averageRating: 4.8,
    totalReviews: 300,
    minimumOrder: 200,
    deliveryFee: 30,
    availabilityStatus: "available",
    schedules: [
      { startTime: "12:00", endTime: "23:00", status: "available" },
    ],
    location: {
      address: "Dhanmondi 27",
      city: "Dhaka",
      area: "Dhanmondi",
      coordinates: { lat: 23.7465, lng: 90.3760 },
    },
    deals: [
      { id: "1", title: "Buy 1 Get 1 (B1G1)", description: "On selected burgers only." },
      { id: "2", title: "Tk 50 off (BOSS50)", description: "Min. order Tk 200." }
    ],
    categories: [
      { name: "Burgers", count: 6 },
      { name: "Fries", count: 2 },
      { name: "Popular", count: 4 }
    ]
  },
  {
    id: "4",
    businessName: "Wrap & Roll",
    profileImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmB8QTlyt_r8AdwPFaD8eg-n0fayf3FrnofA&s",
    bio: "Healthy shawarma wraps",
    specialities: ["Shawarma", "Wraps"],
    averageRating: 4.2,
    totalReviews: 210,
    minimumOrder: 180,
    deliveryFee: 35,
    availabilityStatus: "available",
    schedules: [
      { startTime: "09:00", endTime: "21:00", status: "available" },
    ],
    location: {
      address: "Mirpur 10",
      city: "Dhaka",
      area: "Mirpur",
      coordinates: { lat: 23.8041, lng: 90.3667 },
    },
    deals: [
      { id: "1", title: "Free drink (FREEDRINK)", description: "With every 2 wraps." },
      { id: "2", title: "Tk 30 off (WRAP30)", description: "Min. order Tk 150." }
    ],
    categories: [
      { name: "Wraps", count: 5 },
      { name: "Shawarma", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
  {
    id: "5",
    businessName: "Pasta Palace",
    profileImage: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Italian pasta cooked fresh",
    specialities: ["Pasta", "Italian"],
    averageRating: 4.7,
    totalReviews: 280,
    minimumOrder: 350,
    deliveryFee: 50,
    availabilityStatus: "available",
    schedules: [
      { startTime: "13:00", endTime: "22:30", status: "available" },
    ],
    location: {
      address: "Bashundhara R/A",
      city: "Dhaka",
      area: "Bashundhara",
      coordinates: { lat: 23.8156, lng: 90.4264 },
    },
    deals: [
      { id: "1", title: "15% off (PASTA15)", description: "Valid for all pasta dishes." },
      { id: "2", title: "Free garlic bread (GARLICB)", description: "On orders above Tk 400." }
    ],
    categories: [
      { name: "Pasta", count: 6 },
      { name: "Italian", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
  {
    id: "6",
    businessName: "Tandoori Treats",
    profileImage: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Delicious grilled platters",
    specialities: ["Tandoori", "Grilled"],
    averageRating: 4.4,
    totalReviews: 150,
    minimumOrder: 300,
    deliveryFee: 40,
    availabilityStatus: "available",
    schedules: [
      { startTime: "17:00", endTime: "23:00", status: "available" },
    ],
    location: {
      address: "Uttara Sector 7",
      city: "Dhaka",
      area: "Uttara",
      coordinates: { lat: 23.8761, lng: 90.3790 },
    },
    deals: [
      { id: "1", title: "Tk 60 off (TANDOORI60)", description: "Min. order Tk 250." },
      { id: "2", title: "Free salad (FREESALAD)", description: "With every platter." }
    ],
    categories: [
      { name: "Tandoori", count: 4 },
      { name: "Grilled", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
  {
    id: "7",
    businessName: "Sweet Spoon",
    profileImage: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=facearea&w=400&h=400&q=80",
    bio: "Heavenly desserts",
    specialities: ["Dessert", "Cake", "Ice Cream"],
    averageRating: 4.9,
    totalReviews: 200,
    minimumOrder: 150,
    deliveryFee: 25,
    availabilityStatus: "available",
    schedules: [
      { startTime: "10:00", endTime: "22:00", status: "available" },
    ],
    location: {
      address: "Mohakhali DOHS",
      city: "Dhaka",
      area: "Mohakhali",
      coordinates: { lat: 23.7803, lng: 90.4002 },
    },
    deals: [
      { id: "1", title: "Buy 2 Get 1 (SWEETB2G1)", description: "On all cakes and desserts." },
      { id: "2", title: "Tk 40 off (SWEET40)", description: "Min. order Tk 200." }
    ],
    categories: [
      { name: "Desserts", count: 5 },
      { name: "Cakes", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
  {
    id: "8",
    businessName: "Chopsticks",
    profileImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmB8QTlyt_r8AdwPFaD8eg-n0fayf3FrnofA&s",
    bio: "Asian street food",
    specialities: ["Chinese", "Asian Fusion"],
    averageRating: 4.5,
    totalReviews: 320,
    minimumOrder: 280,
    deliveryFee: 38,
    availabilityStatus: "available",
    schedules: [
      { startTime: "12:00", endTime: "21:30", status: "available" },
    ],
    location: {
      address: "Panthapath",
      city: "Dhaka",
      area: "Panthapath",
      coordinates: { lat: 23.7509, lng: 90.3867 },
    },
    deals: [
      { id: "1", title: "Tk 70 off (CHOP70)", description: "Min. order Tk 250." },
      { id: "2", title: "Free spring roll (FREESPRING)", description: "On orders above Tk 400." }
    ],
    categories: [
      { name: "Chinese", count: 4 },
      { name: "Asian Fusion", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
  {
    id: "9",
    businessName: "Foodie’s Paradise",
    profileImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmB8QTlyt_r8AdwPFaD8eg-n0fayf3FrnofA&s",
    bio: "All-in-one food haven",
    specialities: ["Burger", "Pizza", "Pasta"],
    averageRating: 4.6,
    totalReviews: 480,
    minimumOrder: 350,
    deliveryFee: 45,
    availabilityStatus: "available",
    schedules: [
      { startTime: "10:30", endTime: "23:30", status: "available" },
    ],
    location: {
      address: "Shantinagar",
      city: "Dhaka",
      area: "Shantinagar",
      coordinates: { lat: 23.7383, lng: 90.4179 },
    },
    deals: [
      { id: "1", title: "Tk 125 off (DEALNAO)", description: "Min. order Tk 500. Valid for all items. Use in cart." },
      { id: "2", title: "17% off (NAGAD60)", description: "Min. order Tk 350. Valid for all items. Use in cart." }
    ],
    categories: [
      { name: "Popular", count: 6 },
      { name: "Wrap", count: 5 },
      { name: "Rice Bowl", count: 4 },
      { name: "Signature Item", count: 4 },
      { name: "Platter", count: 6 },
      { name: "Hummus", count: 5 },
      { name: "Fry Box", count: 4 },
      { name: "Daja", count: 2 }
    ]
  },
  {
    id: "10",
    businessName: "Grill & More",
    profileImage: "https://b.zmtcdn.com/data/pictures/2/21393912/7556a6f3ac0fee9eeb85a435cb26a1f3_featured_v2.jpg",
    bio: "Barbecue & steaks",
    specialities: ["BBQ", "Steak", "Western"],
    averageRating: 4.3,
    totalReviews: 190,
    minimumOrder: 300,
    deliveryFee: 40,
    availabilityStatus: "available",
    schedules: [
      { startTime: "15:00", endTime: "22:30", status: "available" },
    ],
    location: {
      address: "Wari",
      city: "Dhaka",
      area: "Wari",
      coordinates: { lat: 23.7196, lng: 90.4213 },
    },
    deals: [
      { id: "1", title: "Tk 90 off (GRILL90)", description: "Min. order Tk 250." },
      { id: "2", title: "Free drink (FREEDRINK)", description: "With every steak order." }
    ],
    categories: [
      { name: "BBQ", count: 4 },
      { name: "Steak", count: 3 },
      { name: "Popular", count: 2 }
    ]
  },
];

export const foodListData = [
  {
    name: "Cheesy Margherita Pizza",
    description: "Classic pizza topped with fresh mozzarella, tomatoes, and basil.",
    price: 550,
    discountedPrice: 499,
    isDiscounted: true,
    portionSize: "12-inch",
    preparationTime: 20,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a1"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Grilled Chicken Burger",
    description: "Juicy grilled chicken patty with lettuce and mayo in a soft bun.",
    price: 350,
    discountedPrice: 299,
    isDiscounted: true,
    portionSize: "Single",
    preparationTime: 15,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a2"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces.",
    price: 420,
    discountedPrice: 379,
    isDiscounted: true,
    portionSize: "1 Plate",
    preparationTime: 25,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a3"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Beef Steak",
    description: "Perfectly grilled steak with sides of mashed potatoes and veggies.",
    price: 750,
    discountedPrice: 699,
    isDiscounted: true,
    portionSize: "200g",
    preparationTime: 30,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a4"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Tandoori Chicken",
    description: "Spicy marinated chicken grilled in a tandoor oven.",
    price: 400,
    discountedPrice: 360,
    isDiscounted: true,
    portionSize: "Half",
    preparationTime: 20,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a3"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Sushi Combo",
    description: "Assorted sushi rolls with wasabi and soy sauce.",
    price: 850,
    discountedPrice: 799,
    isDiscounted: true,
    portionSize: "12 pcs",
    preparationTime: 35,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a5"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Chicken Biryani",
    description: "Aromatic basmati rice cooked with marinated chicken and spices.",
    price: 300,
    discountedPrice: 270,
    isDiscounted: true,
    portionSize: "1 Plate",
    preparationTime: 25,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a6"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Caesar Salad",
    description: "Crisp lettuce, parmesan cheese, and croutons with Caesar dressing.",
    price: 250,
    discountedPrice: 220,
    isDiscounted: true,
    portionSize: "Medium",
    preparationTime: 10,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a7"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Momo Platter",
    description: "Steamed and fried momos with spicy dip.",
    price: 180,
    discountedPrice: 150,
    isDiscounted: true,
    portionSize: "10 pcs",
    preparationTime: 15,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a8"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Pasta Alfredo",
    description: "Creamy Alfredo pasta with mushrooms and cheese.",
    price: 350,
    discountedPrice: 310,
    isDiscounted: true,
    portionSize: "Regular",
    preparationTime: 20,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a9"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Fried Rice & Chicken",
    description: "Egg fried rice with spicy chicken sides.",
    price: 290,
    discountedPrice: 250,
    isDiscounted: true,
    portionSize: "1 Plate",
    preparationTime: 15,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a10"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Ice Cream Sundae",
    description: "Vanilla and chocolate ice cream topped with syrup and nuts.",
    price: 120,
    discountedPrice: 99,
    isDiscounted: true,
    portionSize: "1 Cup",
    preparationTime: 5,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a11"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Paneer Tikka",
    description: "Chunks of paneer grilled with spicy marinade.",
    price: 320,
    discountedPrice: 280,
    isDiscounted: true,
    portionSize: "6 pcs",
    preparationTime: 18,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a3"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Veggie Pizza",
    description: "Loaded with bell peppers, onions, and cheese.",
    price: 500,
    discountedPrice: 450,
    isDiscounted: true,
    portionSize: "12-inch",
    preparationTime: 20,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a1"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Chocolate Cake Slice",
    description: "Rich chocolate cake slice with fudge layer.",
    price: 180,
    discountedPrice: 160,
    isDiscounted: true,
    portionSize: "1 Slice",
    preparationTime: 0,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: false,
    categories: ["a12"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Shawarma Roll",
    description: "Middle Eastern wrap filled with grilled chicken and sauces.",
    price: 220,
    discountedPrice: 200,
    isDiscounted: true,
    portionSize: "Single",
    preparationTime: 0,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a13"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "French Fries",
    description: "Crispy golden fries with ketchup.",
    price: 100,
    discountedPrice: 90,
    isDiscounted: true,
    portionSize: "Medium",
    preparationTime: 7,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a14"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Veg Thali",
    description: "Indian veg thali with rice, chapati, curry, dal & sweet.",
    price: 300,
    discountedPrice: 280,
    isDiscounted: true,
    portionSize: "Full",
    preparationTime: 30,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a15"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Falafel Wrap",
    description: "Crispy falafel balls with hummus and veggies in pita wrap.",
    price: 200,
    discountedPrice: 180,
    isDiscounted: true,
    portionSize: "Single",
    preparationTime: 12,
    isAvailable: true,
    isPopular: false,
    isSuperSaver: false,
    categories: ["a16"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  },
  {
    name: "Masala Dosa",
    description: "Crispy dosa filled with spicy potato stuffing, served with chutney.",
    price: 180,
    discountedPrice: 150,
    isDiscounted: true,
    portionSize: "Single",
    preparationTime: 15,
    isAvailable: true,
    isPopular: true,
    isSuperSaver: true,
    categories: ["a17"],
    photos: ["https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192"],
    id: Math.floor(Math.random() * 100000)
  }
];


export const categories: CategoryType[] = [
  {
    id: "1",
    name: "Pizza",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/73.png?height=192",
  },
  {
    id: "2",
    name: "Burger",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/74.png?height=192",
  },
  {
    id: "3",
    name: "Pasta",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/75.png?height=192",
  },
  {
    id: "4",
    name: "Sushi",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/76.png?height=192",
  },
  {
    id: "5",
    name: "Desserts",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/77.png?height=192",
  },
  {
    id: "6",
    name: "Salads",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/78.png?height=192",
  },
  {
    id: "7",
    name: "BBQ",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/79.png?height=192",
  },
  {
    id: "8",
    name: "Seafood",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/80.png?height=192",
  },
  {
    id: "9",
    name: "Indian",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/81.png?height=192",
  },
  {
    id: "10",
    name: "Chinese",
    image: "https://images.deliveryhero.io/image/foodpanda/cuisine-images/BD/82.png?height=192",
  },
];


export const foodCategoryDummyData: FoodCategoryItem[] = [
    {
        id: "1",
        name: "Beef Bolognese Pasta",
        description: "Tasty minced beef in tomato herb sauce",
        price: 799,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        category: "Pasta",
    },
    {
        id: "2",
        name: "Baked Beef Lasagna",
        description: "A traditional favorite in Italy",
        price: 849,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Pasta",
    },
    {
        id: "3",
        name: "Creamy Chicken",
        description: "Chicken in smooth & creamy sauce",
        price: 799,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Chicken",
    },
    {
        id: "4",
        name: "Pizza Margherita",
        description: "Topped with mozzarella cheese, pizza & tomato",
        price: 499,
        image: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=400&q=80",
        category: "Pizza",
    },
    {
        id: "5",
        name: "Prawn Aglio",
        description: "Prawns with garlic and olive oil",
        price: 789,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Seafood",
    },
    {
        id: "6",
        name: "Chicken Alfredo Pasta",
        description: "Creamy Alfredo sauce with grilled chicken",
        price: 820,
        image: "https://images.unsplash.com/photo-1523987355523-c7b5b0723c6b?auto=format&fit=crop&w=400&q=80",
        category: "Pasta",
    },
    {
        id: "7",
        name: "Spicy Tuna Sushi",
        description: "Fresh tuna with spicy mayo",
        price: 950,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        category: "Sushi",
    },
    {
        id: "8",
        name: "Classic Cheeseburger",
        description: "Beef patty, cheddar cheese, lettuce, tomato",
        price: 550,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Burger",
    },
    {
        id: "9",
        name: "Chicken Caesar Salad",
        description: "Grilled chicken, romaine, Caesar dressing",
        price: 420,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Salad",
    },
    {
        id: "10",
        name: "BBQ Chicken Pizza",
        description: "Barbecue sauce, chicken, onions, cheese",
        price: 670,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Pizza",
    },
    {
        id: "11",
        name: "Vegetable Spring Rolls",
        description: "Crispy rolls with mixed veggies",
        price: 250,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "12",
        name: "Paneer Tikka Masala",
        description: "Grilled paneer in spicy tomato sauce",
        price: 600,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Indian",
    },
    {
        id: "13",
        name: "Fish & Chips",
        description: "Crispy battered fish with fries",
        price: 720,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Seafood",
    },
    {
        id: "14",
        name: "Egg Fried Rice",
        description: "Stir-fried rice with eggs and veggies",
        price: 350,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Chinese",
    },
    {
        id: "15",
        name: "Butter Chicken",
        description: "Creamy tomato-based chicken curry",
        price: 680,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Indian",
    },
    {
        id: "16",
        name: "Tandoori Roti",
        description: "Whole wheat flatbread baked in tandoor",
        price: 60,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Bread",
    },
    {
        id: "17",
        name: "Greek Salad",
        description: "Feta cheese, olives, cucumber, tomato",
        price: 390,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Salad",
    },
    {
        id: "18",
        name: "Chicken Shawarma Wrap",
        description: "Grilled chicken, veggies, garlic sauce",
        price: 320,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Wrap",
    },
    {
        id: "19",
        name: "Classic Hummus",
        description: "Creamy chickpea dip with olive oil",
        price: 220,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "20",
        name: "Chocolate Lava Cake",
        description: "Warm chocolate cake with gooey center",
        price: 350,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Dessert",
    },
    {
        id: "21",
        name: "Garlic Butter Shrimp",
        description: "Shrimp sautéed in garlic butter sauce",
        price: 950,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Seafood",
    },
    {
        id: "22",
        name: "Veggie Burger",
        description: "Grilled veggie patty, lettuce, tomato",
        price: 480,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Burger",
    },
    {
        id: "23",
        name: "Chicken Tikka Pizza",
        description: "Pizza topped with spicy chicken tikka",
        price: 720,
        image: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=400&q=80",
        category: "Pizza",
    },
    {
        id: "24",
        name: "Mushroom Risotto",
        description: "Creamy risotto with mushrooms",
        price: 670,
        image: "https://images.unsplash.com/photo-1523987355523-c7b5b0723c6b?auto=format&fit=crop&w=400&q=80",
        category: "Rice",
    },
    {
        id: "25",
        name: "Falafel Plate",
        description: "Crispy falafel balls, salad, tahini sauce",
        price: 410,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "26",
        name: "Eggplant Parmesan",
        description: "Breaded eggplant, marinara, cheese",
        price: 540,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Italian",
    },
    {
        id: "27",
        name: "Chicken Fried Rice",
        description: "Fried rice with chicken and veggies",
        price: 390,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Chinese",
    },
    {
        id: "28",
        name: "Classic Club Sandwich",
        description: "Triple layered sandwich with chicken, egg, veggies",
        price: 350,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Sandwich",
    },
    {
        id: "29",
        name: "Lamb Kebab",
        description: "Grilled lamb skewers with spices",
        price: 880,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Grill",
    },
    {
        id: "30",
        name: "Vegetable Biryani",
        description: "Spiced rice with mixed vegetables",
        price: 370,
        image: "https://images.unsplash.com/photo-1523987355523-c7b5b0723c6b?auto=format&fit=crop&w=400&q=80",
        category: "Rice",
    },
    {
        id: "31",
        name: "Chicken Nuggets",
        description: "Breaded chicken nuggets with dip",
        price: 260,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "32",
        name: "Pesto Pasta",
        description: "Pasta tossed in basil pesto sauce",
        price: 690,
        image: "https://images.unsplash.com/photo-1523987355523-c7b5b0723c6b?auto=format&fit=crop&w=400&q=80",
        category: "Pasta",
    },
    {
        id: "33",
        name: "Fish Curry",
        description: "Fish cooked in spicy curry sauce",
        price: 720,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Seafood",
    },
    {
        id: "34",
        name: "Chicken Quesadilla",
        description: "Grilled tortilla with chicken and cheese",
        price: 480,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Mexican",
    },
    {
        id: "35",
        name: "Classic Pancakes",
        description: "Fluffy pancakes with syrup",
        price: 300,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Breakfast",
    },
    {
        id: "36",
        name: "Shrimp Tempura",
        description: "Crispy battered shrimp",
        price: 850,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Seafood",
    },
    {
        id: "37",
        name: "Veggie Omelette",
        description: "Egg omelette with mixed veggies",
        price: 220,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Breakfast",
    },
    {
        id: "38",
        name: "Chicken Satay",
        description: "Grilled chicken skewers with peanut sauce",
        price: 540,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "39",
        name: "Classic Tiramisu",
        description: "Coffee-flavored Italian dessert",
        price: 420,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Dessert",
    },
    {
        id: "40",
        name: "Chicken Katsu Curry",
        description: "Breaded chicken cutlet with curry sauce",
        price: 690,
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        category: "Japanese",
    },
    {
        id: "41",
        name: "Classic BLT Sandwich",
        description: "Bacon, lettuce, tomato on toasted bread",
        price: 350,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Sandwich",
    },
    {
        id: "42",
        name: "Vegetable Samosa",
        description: "Crispy pastry filled with spiced veggies",
        price: 120,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Appetizer",
    },
    {
        id: "43",
        name: "Chicken Burrito",
        description: "Flour tortilla stuffed with chicken, beans, rice",
        price: 480,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Mexican",
    },
    {
        id: "44",
        name: "Classic Cheesecake",
        description: "Creamy cheesecake with biscuit base",
        price: 390,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Dessert",
    },
    {
        id: "45",
        name: "Chicken Manchurian",
        description: "Fried chicken balls in tangy sauce",
        price: 520,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Chinese",
    },
    {
        id: "46",
        name: "Classic French Toast",
        description: "Bread soaked in egg, fried, served with syrup",
        price: 260,
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        category: "Breakfast",
    },
    {
        id: "47",
        name: "Chicken Alfredo Pizza",
        description: "Pizza with Alfredo sauce, chicken, cheese",
        price: 720,
        image: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=400&q=80",
        category: "Pizza",
    },
    {
        id: "48",
        name: "Classic Caesar Salad",
        description: "Romaine, croutons, Caesar dressing",
        price: 350,
        image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80",
        category: "Salad",
    },
    {
        id: "49",
        name: "Classic Veggie Pizza",
        description: "Pizza with bell peppers, onions, olives",
        price: 650,
        image: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=400&q=80",
        category: "Pizza",
    },
    {
        id: "50",
        name: "Classic Chicken Burger",
        description: "Fried chicken patty, lettuce, mayo, bun",
        price: 570,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80",
        category: "Burger",
    },
];
